version: '3.8'

services:
  app:
    build: .
    ports:
      - '4080:4080'
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=login123!
      - DB_NAME=map_coordinates
      - DB_PORT=5432
    depends_on:
      - mdb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mdb:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: login123!
      POSTGRES_DB: map_coordinates
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
